name: attendloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  dropdown_search: ^5.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  geolocator: ^12.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.6.0
  intl: ^0.18.0
  location: ^6.0.0
  lottie: ^3.1.2
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: any
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/resources/

flutter:
  uses-material-design: true
  assets:
    - lib/resources/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
